language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - COMPOSER_FLAGS="--prefer-lowest" TEST_SUITE="success"
  - COMPOSER_FLAGS="--prefer-stable" TEST_SUITE="success"
  - COMPOSER_FLAGS="--prefer-lowest" TEST_SUITE="failure"
  - COMPOSER_FLAGS="--prefer-stable" TEST_SUITE="failure"

matrix:
  allow_failures:
  - php: 7.0
    env: COMPOSER_FLAGS="--prefer-lowest" TEST_SUITE="failure"
  - php: 7.0
    env: COMPOSER_FLAGS="--prefer-stable" TEST_SUITE="failure"
  - php: 7.1
    env: COMPOSER_FLAGS="--prefer-lowest" TEST_SUITE="failure"
  - php: 7.1
    env: COMPOSER_FLAGS="--prefer-stable" TEST_SUITE="failure"
  - php: 7.2
    env: COMPOSER_FLAGS="--prefer-lowest" TEST_SUITE="failure"
  - php: 7.2
    env: COMPOSER_FLAGS="--prefer-stable" TEST_SUITE="failure"

install:
  - composer update $COMPOSER_FLAGS

script:
  - composer validate --strict
  - vendor/bin/phpunit --testsuite $TEST_SUITE
