language: php

sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS="--prefer-stable"
  - TEST_SUITE="success"
  - TEST_SUITE="failure"

matrix:
  allow_failures:
  - TEST_SUITE="failure"

install:
  - composer update $COMPOSER_FLAGS

script:
  - composer validate --strict
  - vendor/bin/phpunit --testsuite $TEST_SUITE
